[2025-01-22T09:18:45.947+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T09:18:45.956+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branching_2.branching manual__2025-01-22T09:18:44.706875+00:00 [queued]>
[2025-01-22T09:18:45.962+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branching_2.branching manual__2025-01-22T09:18:44.706875+00:00 [queued]>
[2025-01-22T09:18:45.963+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-22T09:18:45.973+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): branching> on 2025-01-22 09:18:44.706875+00:00
[2025-01-22T09:18:45.977+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=729) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-22T09:18:45.979+0000] {standard_task_runner.py:72} INFO - Started process 730 to run task
[2025-01-22T09:18:45.978+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'branching_2', 'branching', 'manual__2025-01-22T09:18:44.706875+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/b.py', '--cfg-path', '/tmp/tmpkqe9t3ov']
[2025-01-22T09:18:45.980+0000] {standard_task_runner.py:105} INFO - Job 194: Subtask branching
[2025-01-22T09:18:46.008+0000] {task_command.py:467} INFO - Running <TaskInstance: branching_2.branching manual__2025-01-22T09:18:44.706875+00:00 [running]> on host 7854821b9569
[2025-01-22T09:18:46.054+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branching_2' AIRFLOW_CTX_TASK_ID='branching' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T09:18:44.706875+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T09:18:44.706875+00:00'
[2025-01-22T09:18:46.055+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T09:18:46.063+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-22T09:18:46.070+0000] {python.py:240} INFO - Done. Returned value was: can_drive
[2025-01-22T09:18:46.070+0000] {branch.py:38} INFO - Branch into can_drive
[2025-01-22T09:18:46.071+0000] {skipmixin.py:230} INFO - Following branch ('can_drive',)
[2025-01-22T09:18:46.077+0000] {skipmixin.py:278} INFO - Skipping tasks [('cant_drive', -1)]
[2025-01-22T09:18:46.095+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T09:18:46.096+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=branching_2, task_id=branching, run_id=manual__2025-01-22T09:18:44.706875+00:00, execution_date=20250122T091844, start_date=20250122T091845, end_date=20250122T091846
[2025-01-22T09:18:46.155+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T09:18:46.174+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-22T09:18:46.179+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
