[2025-01-21T09:36:42.957+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-21T09:36:42.966+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: branching.verify_driving_licence manual__2025-01-21T09:36:41.197320+00:00 [queued]>
[2025-01-21T09:36:42.972+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: branching.verify_driving_licence manual__2025-01-21T09:36:41.197320+00:00 [queued]>
[2025-01-21T09:36:42.973+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-21T09:36:42.981+0000] {taskinstance.py:2889} INFO - Executing <Task(BranchPythonOperator): verify_driving_licence> on 2025-01-21 09:36:41.197320+00:00
[2025-01-21T09:36:42.986+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=955) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-21T09:36:42.987+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'branching', 'verify_driving_licence', 'manual__2025-01-21T09:36:41.197320+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/branching.py', '--cfg-path', '/tmp/tmpcc_r8nqh']
[2025-01-21T09:36:42.988+0000] {standard_task_runner.py:72} INFO - Started process 956 to run task
[2025-01-21T09:36:42.988+0000] {standard_task_runner.py:105} INFO - Job 180: Subtask verify_driving_licence
[2025-01-21T09:36:43.014+0000] {task_command.py:467} INFO - Running <TaskInstance: branching.verify_driving_licence manual__2025-01-21T09:36:41.197320+00:00 [running]> on host 7854821b9569
[2025-01-21T09:36:43.064+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='branching' AIRFLOW_CTX_TASK_ID='verify_driving_licence' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T09:36:41.197320+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-21T09:36:41.197320+00:00'
[2025-01-21T09:36:43.065+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-21T09:36:43.074+0000] {baseoperator.py:421} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-21T09:36:43.081+0000] {python.py:240} INFO - Done. Returned value was: can_drive
[2025-01-21T09:36:43.081+0000] {branch.py:38} INFO - Branch into can_drive
[2025-01-21T09:36:43.082+0000] {skipmixin.py:230} INFO - Following branch ('can_drive',)
[2025-01-21T09:36:43.087+0000] {skipmixin.py:278} INFO - Skipping tasks [('cant_drive', -1)]
[2025-01-21T09:36:43.107+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-21T09:36:43.108+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=branching, task_id=verify_driving_licence, run_id=manual__2025-01-21T09:36:41.197320+00:00, execution_date=20250121T093641, start_date=20250121T093642, end_date=20250121T093643
[2025-01-21T09:36:43.161+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-21T09:36:43.180+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-21T09:36:43.185+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
